#!/bin/sh

source "$CONFIG_DIR/colors.sh"

# Bar appearance
sketchybar --bar position=top \
           height=32 \
           blur_radius=40 \
           y_offset=4 \
           margin=12 \
           corner_radius=12 \
           padding_left=0 \
           padding_right=0 \
           color=0x20000000 \
           border_color=0x20FFFFFF \
           border_width=1 \
           shadow=on \
           shadow.color=0x80000000 \
           shadow.distance=8 \
           shadow.angle=270

# Default item properties
sketchybar --default \
           padding_left=4 \
           padding_right=4 \
           icon.font="SF Pro:Semibold:14.0" \
           label.font="SF Mono:Semibold:12.0s" \
           icon.color=$WHITE \
           label.color=$WHITE \
           icon.padding_left=8 \
           icon.padding_right=4 \
           label.padding_left=4 \
           label.padding_right=8 \
           background.color=$ITEM_BG_COLOR \
           background.corner_radius=5 \
           background.height=24

# Left side:
# Workspaces
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_focus_change

for sid in $(aerospace list-workspaces --all); do
  sketchybar --add item space.$sid left \
             --subscribe space.$sid aerospace_workspace_change \
             --subscribe space.$sid aerospace_focus_change \
             --set space.$sid \
             icon=$sid \
             icon.font="SF Pro:Semibold:10.0" \
             label.font="sketchybar-app-font:Regular:12.0" \
             label.padding_right=8 \
             label.y_offset=-1 \
             click_script="aerospace workspace $sid" \
             script="$CONFIG_DIR/scripts/aerospace.sh $sid"
done

# Separator
sketchybar --add item space_separator left \
           --set space_separator \
           icon="􀆊" \
           icon.color=$ACCENT_COLOR \
           icon.padding_left=4 \
           label.drawing=off \
           background.drawing=off \
           --subscribe space_separator aerospace_workspace_change

# Right side:
# Time & Date
sketchybar --add item calendar right \
           --set calendar update_freq=30 \
           icon.padding_left=0 \
           background.color=0x00000000 \
           script="$CONFIG_DIR/scripts/calendar.sh"

# Battery
sketchybar --add item battery right \
           --set battery update_freq=120 \
                  background.color=0x00000000 \
                  script="$CONFIG_DIR/scripts/battery.sh" \
           --subscribe battery system_woke power_source_change

# CPU
sketchybar --add item cpu right \
           --set cpu update_freq=2 \
                  icon=􀧓 \
                  background.color=0x00000000 \
                  script="$CONFIG_DIR/scripts/cpu.sh" \
                  click_script="open /Applications/Utilities/Activity\ Monitor\ alias"
                  
# Volume
sketchybar --add item volume right \
           --set volume background.color=0x00000000 \
                       script="$CONFIG_DIR/scripts/volume.sh" \
           --subscribe volume volume_change


# Front app
sketchybar --add item front_app right \
           --set front_app \
           icon.drawing=off \
           label.padding_left=8 \
           label.padding_right=8 \
           background.corner_radius=8 \
           background.color=$ITEM_BG_COLOR \
           label.color=$LABEL_COLOR \
           script="$CONFIG_DIR/scripts/front_app.sh" \
           --subscribe front_app front_app_switched

NAME=${NAME:-icalPal}
POS=${POS:-right}


##################################################
# Set some icalPal options

export ICALPAL='--days 10 --li 10 --ec Birthdays'
UPDATE_FREQ=$((15 * 60))	# Update the events every 15 minutes
EXE=icalPal

##################################################
# Add the item

sketchybar --add item "${NAME}" "${POS}" \
	   --set "${NAME}" label="$(date "+%b %e")" \
	   --set "${NAME}" popup.align="${POS}" popup.background.drawing=off \
	   --set "${NAME}" update_freq="${UPDATE_FREQ}" \
	   --set "${NAME}" script="EXE=\"${EXE}\" ICALPAL=\"${ICALPAL}\" ${CONFIG_DIR}/scripts/icalPal.sh" \
	   --subscribe "${NAME}" mouse.{clicked,exited} mouse.exited.global

source "$CONFIG_DIR/scripts/aerospace-icons.sh"

# Force all scripts to run the first time
sketchybar --update
